// Fallback data used when database is unavailable
// Extracted from the original V0 template static content

export const defaultProductCategories = [
  {
    id: "diagnostic",
    icon_name: "Activity",
    title: "診斷設備",
    subtitle: "Diagnostic Equipment",
    description: "提供先進的全自動臨床生化分析儀，只需 0.1cc 全血即可在 12 分鐘內完成 22 項生化檢查，大幅提升診斷效率。",
    products: [
      {
        id: "biochem-analyzer",
        name: "全自動臨床生化分析儀",
        model: "LOCMEDT",
        description: "動物用全自動臨床生化分析儀，只需 90~120uL 全血，12 分鐘自動完成 22 項生化檢查，自動離心稀釋、自動 QC。",
        features: ["僅需 0.1cc 全血", "12 分鐘完成檢測", "22 項生化檢查", "自動離心稀釋", "自動品質控制", "操作簡便快速"],
        specs: { "檢體需求": "90~120μL 全血", "檢測時間": "約 12 分鐘", "檢測項目": "22 項生化指標", "特色功能": "自動離心、稀釋、QC" },
        highlight: true,
      },
      {
        id: "test-disc",
        name: "生化檢驗試片盤",
        model: "專用耗材",
        description: "搭配全自動生化分析儀使用的專用試片盤，確保檢測結果的準確性與一致性。",
        features: ["高精準度檢測", "穩定品質控制", "長效保存期限", "即開即用設計"],
        specs: { "適用機型": "LOCMEDT 生化分析儀", "保存方式": "冷藏保存", "包裝規格": "請洽詢業務" },
      },
      {
        id: "fluorescence-analyzer",
        name: "免疫螢光分析儀",
        model: "進階檢測",
        description: "提供更精密的免疫螢光檢測功能，適用於特殊項目的定量分析。",
        features: ["高靈敏度檢測", "定量分析結果", "多項目檢測", "數據管理系統"],
        specs: { "檢測原理": "免疫螢光法", "應用範圍": "特殊項目定量分析" },
      },
    ],
  },
  {
    id: "rapid",
    icon_name: "TestTube",
    title: "快篩試劑",
    subtitle: "Rapid Test Kits",
    description: "完整的膠體金快篩產品線，涵蓋貓毛滴蟲、犬下痢套組、抗體力價檢測等，協助獸醫師快速準確診斷。",
    products: [
      {
        id: "cat-trichomonas",
        name: "貓毛滴蟲抗原快篩",
        model: "Feline Tritrichomonas Ag",
        description: "貓感染毛滴蟲會造成反覆慢性下痢、血痢、黏液便、消瘦等症狀，且可能被誤判為梨形鞭毛蟲感染導致無效治療。",
        features: ["快速精準診斷", "避免誤判梨形鞭毛蟲", "簡易操作流程", "結果判讀清晰"],
        specs: { "檢體類型": "糞便檢體", "判讀時間": "10-15 分鐘", "保存條件": "2-30°C" },
        highlight: true,
      },
      {
        id: "canine-diarrhea",
        name: "犬下痢套組",
        model: "4-in-1 Canine Diarrhea Panel",
        description: "為全齡犬常見消化道傳染病提供完整檢查，包含犬小病毒、冠狀病毒、梨型鞭毛蟲及輪狀病毒檢測。",
        features: ["四合一完整檢測", "犬小病毒 (CPV)", "冠狀病毒 (CCV)", "梨型鞭毛蟲 (Giardia)", "輪狀病毒 (Rotavirus)"],
        specs: { "檢測項目": "4 種病原", "適用對象": "全齡犬", "檢體類型": "糞便檢體" },
        highlight: true,
      },
      {
        id: "antibody-titer",
        name: "抗體力價檢測",
        model: "Antibody Titer Test",
        description: "適用於接種疫苗前後、健康檢查、疑似早期病毒感染、或動物經歷外宿寄養等可能交叉感染場所後使用。",
        features: ["評估免疫狀態", "疫苗效果確認", "早期感染偵測", "需搭配判讀機"],
        specs: { "適用時機": "疫苗接種前後、健康檢查", "檢體類型": "血清/全血", "注意事項": "需搭配快篩判讀機使用" },
      },
      {
        id: "reader",
        name: "快篩判讀機",
        model: "Reader Device",
        description: "搭配抗體力價檢測使用，提供客觀準確的數值判讀結果。",
        features: ["數位化判讀", "結果客觀準確", "數據可追溯", "操作簡便"],
        specs: { "功能": "快篩結果數位判讀", "適用產品": "抗體力價檢測試劑" },
      },
    ],
  },
  {
    id: "wound",
    icon_name: "Stethoscope",
    title: "傷口護理",
    subtitle: "Wound Care",
    description: "專業的傷口護理產品，包含高濃度銀離子凝膠、藻酸鈣銀敷料等，有效促進傷口癒合並預防感染。",
    products: [
      {
        id: "silver-gel",
        name: "高濃度銀離子凝膠",
        model: "Silver Ion Gel",
        description: "含高濃度銀離子的傷口護理凝膠，具有優異的抗菌效果，有效預防傷口感染並促進癒合。",
        features: ["高濃度銀離子", "廣效抗菌作用", "促進傷口癒合", "減少感染風險"],
        specs: { "主要成分": "銀離子", "適用範圍": "各類傷口護理", "使用方式": "外用塗抹" },
        highlight: true,
      },
      {
        id: "alginate-silver",
        name: "藻酸鈣銀敷料",
        model: "Alginate Silver Dressing",
        description: "結合藻酸鈣與銀離子的高級敷料，適用於中度至重度滲出液傷口，提供濕潤癒合環境。",
        features: ["吸收滲出液", "維持濕潤環境", "銀離子抗菌", "促進肉芽生長"],
        specs: { "材質": "藻酸鈣 + 銀離子", "適用傷口": "中重度滲出液傷口" },
      },
      {
        id: "spray-bottle",
        name: "儲霧瓶",
        model: "Spray Bottle",
        description: "專業醫療級儲霧瓶，可搭配各類傷口護理液使用，噴霧均勻細緻。",
        features: ["醫療級材質", "噴霧均勻", "使用便利", "可重複使用"],
        specs: { "材質": "醫療級塑料", "容量": "請洽詢業務" },
      },
      {
        id: "elastic-bandage",
        name: "動物用彈性繃帶",
        model: "Elastic Bandage",
        description: "專為動物設計的彈性繃帶，具有良好的延展性與固定效果，不易被動物咬破。",
        features: ["高彈性材質", "固定效果佳", "透氣舒適", "不易被咬破"],
        specs: { "特性": "高彈性、透氣", "適用對象": "各類動物" },
      },
    ],
  },
  {
    id: "surgical",
    icon_name: "Scissors",
    title: "手術耗材",
    subtitle: "Surgical Supplies",
    description: "提供動物專用組織膠、拋棄式切割吻合器、皮釘等手術耗材，以及專業的電漿滅菌服務。",
    products: [
      {
        id: "tissue-glue",
        name: "動物專用組織膠",
        model: "Veterinary Tissue Adhesive",
        description: "專為動物手術設計的組織膠，可快速黏合傷口，減少縫合需求，降低手術時間。",
        features: ["快速黏合", "減少縫合", "降低手術時間", "傷口美觀"],
        specs: { "適用範圍": "皮膚及軟組織", "黏合時間": "快速", "特點": "減少縫線使用" },
        highlight: true,
      },
      {
        id: "stapler",
        name: "直線切割吻合器",
        model: "Linear Cutter Stapler",
        description: "拋棄式直線切割吻合器，提供精準的組織切割與吻合，適用於各類外科手術。",
        features: ["精準切割", "可靠吻合", "拋棄式設計", "降低感染風險"],
        specs: { "類型": "拋棄式", "功能": "切割 + 吻合" },
      },
      {
        id: "skin-stapler",
        name: "拋棄式皮釘",
        model: "Disposable Skin Stapler",
        description: "快速便利的皮膚縫合方案，適用於線性傷口的快速閉合。",
        features: ["快速縫合", "操作簡便", "傷口整齊", "拋棄式衛生"],
        specs: { "類型": "拋棄式", "適用": "線性皮膚傷口" },
      },
      {
        id: "sterilization",
        name: "電漿滅菌服務",
        model: "Plasma Sterilization Service",
        description: "提供專業的電漿滅菌服務，適用於不耐高溫高壓的精密醫療器械。",
        features: ["低溫滅菌", "保護精密器械", "滅菌效果確實", "專業服務團隊"],
        specs: { "滅菌方式": "低溫電漿", "適用器械": "不耐高溫精密器材", "服務類型": "委託滅菌" },
        highlight: true,
      },
    ],
  },
]
